# Generated by Django 5.0 on 2023-12-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='фио_клиента')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_mail', models.CharField(choices=[('Ежедневная', 'Раз в день'), ('Еженедельная', 'Раз в неделю'), ('Ежемесячная', 'Раз в месяц')], max_length=25, verbose_name='периодичность_рассылки')),
                ('status_mail', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], max_length=25, verbose_name='статус_рассылки')),
                ('start_mail', models.DateTimeField(blank=True, null=True, verbose_name='время начала рассылки')),
                ('end_mail', models.DateTimeField(blank=True, null=True, verbose_name='время окончания рассылки')),
                ('clients', models.ManyToManyField(to='main.client', verbose_name='клиенты_рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('period_mail',),
            },
        ),
        migrations.CreateModel(
            name='Logfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_log', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status_log', models.BooleanField(choices=[('SENT', 'Отправлено'), ('FAILED', 'Не удалось отправить')], verbose_name='статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=100, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('status_log',),
            },
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_title', models.CharField(max_length=25, verbose_name='Тема_рассылки')),
                ('msg_body', models.TextField(verbose_name='Тело_рассылки')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('msg_title',),
            },
        ),
    ]
