# Generated by Django 5.0 on 2023-12-11 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='end_mail',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='start_mail',
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mailing',
            name='title_mail',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='main.client', verbose_name='Клиенты рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period_mail',
            field=models.CharField(choices=[('Ежедневная', 'Раз в день'), ('Еженедельная', 'Раз в неделю'), ('Ежемесячная', 'Раз в месяц')], max_length=25, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_mail',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], max_length=25, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_body',
            field=models.TextField(verbose_name='Текст письма'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_title',
            field=models.CharField(max_length=25, verbose_name='Тема письма'),
        ),
    ]
